package com.maorgil.hospitalappointmentsystem.beans;

import com.maorgil.hospitalappointmentsystem.DBHandler;
import com.maorgil.hospitalappointmentsystem.Utils;
import com.maorgil.hospitalappointmentsystem.entity.AppointmentsEntity;
import com.maorgil.hospitalappointmentsystem.entity.DoctorsEntity;
import org.primefaces.PrimeFaces;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;

@ViewScoped
@ManagedBean(name = "successAppointmentBean")
public class SuccessAppointmentBean {
    private final AppointmentsEntity appointment;

    private String date = "*";
    private String time = "*";
    private String doctorDetails = "*";
    private String location = "*";

    public SuccessAppointmentBean() {
        String id = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("appId");
        appointment = Utils.idToAppointment(id);

        if (appointment == null)
            return;

        date = appointment.getStartTime().toLocalDateTime().toLocalDate().toString();
        time = appointment.getStartTime().toLocalDateTime().toLocalTime().toString()
                + "-" + appointment.getEndTime().toLocalDateTime().toLocalTime().toString();
        DoctorsEntity doctor = DBHandler.getInstance().getDoctorById(appointment.getDoctorId());
        doctorDetails = doctor.getPresentableName();
        location = doctor.getCity();
    }

    public String getDate() {
        return date;
    }

    public String getTime() {
        return time;
    }

    public String getDoctorDetails() {
        return doctorDetails;
    }

    public String getLocation() {
        return location;
    }

    /**
     * Open a new window with Google Calendar with the appointment details entered
     */
    public void addToGoogleCalendar() {
        DoctorsEntity doctor = DBHandler.getInstance().getDoctorById(appointment.getDoctorId());

        String dates = Utils.datesToGoogleCalendarFormat(
                appointment.getStartTime().toLocalDateTime(),
                appointment.getEndTime().toLocalDateTime());
        String eventName = "Hospital appointment with " + "Dr. " + doctor.getFirstName();
        String details = "Appointment with dr. " + doctorDetails +
                "\n" + doctor.getAbout() +
                "\nGenerated by Hospital Appointment System.";
        String location = "";

        try {
            eventName = URLEncoder.encode(eventName, "UTF-8");
            details = URLEncoder.encode(details, "UTF-8");
            dates = URLEncoder.encode(dates, "UTF-8");
            location = URLEncoder.encode(this.location, "UTF-8");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }

        // Construct the Google Calendar URL with appointment details
        String googleCalendarUrl = "https://calendar.google.com/calendar/render?action=TEMPLATE" +
                "&text=" + eventName +
                "&dates=" + dates +
                "&details=" + details +
                "&location=" + location;


        // Open Google Calendar in a new window with appointment details
        PrimeFaces.current().executeScript("window.open('" + googleCalendarUrl + "','_blank')");
    }
}
